version: "3"
services:
  spark-master:
    image: spark-master:latest
    ports:
      - "4040:4040"
      - "8080:8080"
      - "7077:7077"
    volumes:
       - ./apps:/opt/spark-apps
       - ./data:/opt/spark-data
    environment:
      - "SPARK_LOCAL_IP=spark-master"
      - GOOGLE_PLAY_STORE_PATH=/opt/spark-data/input/googleplaystore.csv
      - GOOGLE_PLAY_STORE_USER_REVIEWS_PATH=/opt/spark-data/input/googleplaystore_user_reviews.csv
      - OUTPUT_PATH=/opt/spark-data/output/

  spark-worker:
    image: spark-worker:latest
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=128m
      - SPARK_EXECUTOR_MEMORY=256m
      - GOOGLE_PLAY_STORE_PATH=/opt/spark-data/input/googleplaystore.csv
      - GOOGLE_PLAY_STORE_USER_REVIEWS_PATH=/opt/spark-data/input/googleplaystore_user_reviews.csv
      - OUTPUT_PATH=/opt/spark-data/output/
    volumes:
       - ./apps:/opt/spark-apps
       - ./data:/opt/spark-data
